replicaCount: 1

image:
  repository: jonathanrogers/saral-backend
  tag: "1.6.2"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3005


replicas:
   Count: 2

profile:
  environment: prod

docdb:
  connection: mongodb://saral_user:MX9QsFla7bZd6t@saral-db.cluster-cfckukum4zxf.ap-south-1.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false/prod_saral

whitelist:
  domain: [https://saral.tekdinext.com, http://saral.tekdinext.com]
