apiVersion: v1
kind: Service
metadata:
  name: {{ include "saral-backend.fullname" . }}
  labels:
    app: saral-backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3005
  selector:
    app: saral-backend

