apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-alert-manager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: prometheus
  resources:
    requests:
      storage: 10Gi
